### PR TITLE
Added option to allow parent reference children.

### PR DESCRIPTION
**Pull request by 0xorial**

### CODE REVIEW

**Comment by realvizu** [comment]
Thanks for contributing!
However I'm not sure that it's a good idea to encourage users to allow parent namespaces to reference their children because child namespaces should be more specific then their parents and generally the direction of dependency should be from more specific to more generic, but let's hope that people don't misuse it.

**Comment by realvizu** [comment]
I will release a new nuget package with this feature in a couple of days.

**Comment by 0xorial** [comment]
Thanks for accepting!

Just out of curiosity - do you have some public repository where I can see how you structure your namespaces?

In my case I usually have child namespaces serve as implementation details of the parent namespace, which in turn contain smth like a facade to the whole namespace (and this applies recursively). Hence there a lot of references from parents to children and the only thing I wanted to forbid was uncontrolled references between sibling (and especially nephew/uncle) namespaces.

**Comment by realvizu** [comment]
Sure, check out this rule file for example: https://github.com/realvizu/QuickDiagram/blob/vs2019/source/SoftVis.Diagramming/config.nsdepcop

Eg.
* Codartis.SoftVis.Modeling contains the "interface" or "facade" of the modeling concepts.
* Its sub-namespace, Codartis.SoftVis.Modeling.Implementation contains implemenation details. It automatically sees the "interface" because ChildCanDependOnParentImplicitly="true" in the solution-wide rule file here: https://github.com/realvizu/QuickDiagram/blob/vs2019/source/config.nsdepcop
* Clients of the modeling concepts (eg. Codartis.SoftVis.UI) are allowed to see Codartis.SoftVis.Modeling, but not its sub-namespaces.  `<Allowed From="Codartis.SoftVis.UI.*" To="Codartis.SoftVis.Modeling" />`
* The host component uses DI to map interfaces to their implementations so it has to see them all, eg.  in https://github.com/realvizu/QuickDiagram/blob/vs2019/source/SoftVis.TestHostApp/config.nsdepcop there's a very liberal rule:  `<Allowed From="Codartis.SoftVis.TestHostApp.*" To="Codartis.SoftVis.*" /> `

When I'm unable to structure the namespaces without parent->child rules then I like to make them explicit, eg. 
`  <Allowed From="Codartis.SoftVis.Diagramming.Layout.Incremental" To="Codartis.SoftVis.Diagramming.Layout.Incremental.Absolute" />`

**Pull request merged**
